apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-config-backend-deployment-v2  # Change the name to a new one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-config
      component: backend
  template:
    metadata:
      labels:
        app: ros-config
        component: backend
    spec:
      containers:
        - name: ros-config-backend
          image: mrneedhelp/adv6_ros_config:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-config-database-deployment-v2  # Change the name to a new one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-config
      component: database
  template:
    metadata:
      labels:
        app: ros-config
        component: database
    spec:
      containers:
        - name: ros-config-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: mysecretuser
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
---
apiVersion: v1
kind: Service
metadata:
  name: ros-config-service
spec:
  selector:
    app: ros-config
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: database-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-config-backend-deployment-v2  # Change the name to a new one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-config
      component: backend
  template:
    metadata:
      labels:
        app: ros-config
        component: backend
    spec:
      containers:
        - name: ros-config-backend
          image: mrneedhelp/adv6_ros_config:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090