// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/ros/control/proto/getter.proto

// Protobuf Java Version: 3.25.2
package com.ros.control.server;

public interface ConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ros.control.server.ConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
