// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/ros/control/proto/getter.proto

// Protobuf Java Version: 3.25.2
package com.ros.control.server;

public final class GetterOuterClass {
  private GetterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ros_control_server_ConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ros_control_server_ConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ros_control_server_ConfigReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ros_control_server_ConfigReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/java/com/ros/control/proto/ge" +
      "tter.proto\022\026com.ros.control.server\032\036goog" +
      "le/protobuf/wrappers.proto\" \n\rConfigRequ" +
      "est\022\017\n\007message\030\001 \001(\t\"{\n\013ConfigReply\022(\n\002i" +
      "d\030\001 \001(\0132\034.google.protobuf.StringValue\022\014\n" +
      "\004port\030\002 \001(\005\022\020\n\010hostname\030\003 \001(\t\022\020\n\010usernam" +
      "e\030\004 \001(\t\022\020\n\010password\030\005 \001(\t2a\n\006Getter\022W\n\tg" +
      "etConfig\022%.com.ros.control.server.Config" +
      "Request\032#.com.ros.control.server.ConfigR" +
      "eplyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_com_ros_control_server_ConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ros_control_server_ConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ros_control_server_ConfigRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_ros_control_server_ConfigReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ros_control_server_ConfigReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ros_control_server_ConfigReply_descriptor,
        new java.lang.String[] { "Id", "Port", "Hostname", "Username", "Password", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
